package com.loan.common.exception;

public enum CommonCode implements ErrorCode
{

  TRANSIT_MA_FAILURE(1),
  ST_INSERT_FAILURE(2),
  MIV_MA_FAILURE(3),
  TV_MA_FAILURE(4),
  MRV_MA_FAILURE(5),
  PB_MA_FAILURE(6), 
  MRV_SA_FAILURE(7),
  MIV_SA_FAILURE(8),
  GR_A_FAILURE(9),
  TRS_ACK_FAILURE(10),
  S_RETURN_SA_FAILURE(11),
  S_RECEIPT_SA_FAILURE(12),
  INSUFFICIENT_METAL_PREMISES_BALANCE(13),
  INSUFFICIENT_METAL_VENDOR_FG_BALANCE(14),
  INSUFFICIENT_METAL_VENDOR_RM_BALANCE(15),
  INSUFFICIENT_STONE_PREMISES_BALANCE(16),
  INSUFFICIENT_STONE_VENDOR_BALANCE(17),
  ERROR_METAL_PREMISES_BALANCE(18),
  ERROR_METAL_VENDOR_FG_BALANCE(19),
  ERROR_METAL_VENDOR_RM_BALANCE(20),
  ERROR_STONE_PREMISES_BALANCE(21),
  ERROR_STONE_VENDOR_BALANCE(22),
  PARAMETER_NOT_FOUND(23);
  
  private final int number;

  private CommonCode(int number)
  {
    this.number = number;
  }

  @Override
  public int getNumber()
  {
    return number;
  }

}
