package com.loan.common.exception;

public enum OECode implements ErrorCode
{

  INVALID_USER(201),
  INVALID_PORTAL(220),
  INVALID_REQUESR(202),
  DESIGN_APPROVE(203),
  CONTACT_ADMIN(204),
  DESIGN_ASSIGN(205),
  MIV_FINISHED_GOODS(206),
  MIV_ISSUED(207),
  STONES_NOT_EXIST(208),
  ACCESSORY_NOT_EXIST(209),
  PSR_NOT_EXIST(210),
  ASSIGN_VENDOR_RELEASE(211),
  NODATA_FOUND(212),  
  INSUFFICIENT_WEIGHT_BALANACE(213),
  ID_NOT_FOUND(214),
  EMAIL_ID_NOT_FOUND(215),
  VENDOR_IS_NOT_REGISTERED(216),
  MRV_UPDATE_FAILURE(217),
  FAS_FAIL_TRANSFER(218),
  FAS_SUCCESS_TRANSFER(219),
  MRV_STONE_ACC_EXIST(220),
  ITEM_DOES_NOT_EXIST(221),
  BOARDRATE_OR_METALPURITY_NOT_FOUND(222),
  ALREADY_RENUMBERD(223),
  SELECT_TRANSFER_VOUCHER(224),
  SESSION_EXPIRED(225),
  STANDERD_RATE_NOT_FOUND(226),
  UNABLE_TO_RENUMBER(227),
  ALREADY_ASSEMBLED(228),
  MOVE_TO_LRN_LOCATION(229),
  PASSWORD_EXPIRE(230);
  
  private final int number;

  private OECode(int number)
  {
    this.number = number;
  }

  @Override
  public int getNumber()
  {
    return number;
  }

}
