package com.loan.common.exception;

public enum SalesCode implements ErrorCode {

	INVALID_USER(101), NODATA_FOUND(102), CONTACT_ADMIN(103), PAYMENT_NOTDONE(
			104), PAYMENT_AMOUNT_ZERO(105), PAYMENT_AMOUNT_NOTMATCH(106), ORDER_NOT_CREATED(
			107), ORDER_LINE_ITEM_NOT_CREATED(108), ORDER_ID_NOTFOUND(109), INVALID_DESIGNER_TYPE(
			110), VOUCHER_ORDERTYPE(111), NOSP_FOUND(112), INVALID_DATEFORMAT(
			113), CUST_ORDER_ID_NOTFOUND(114), CUST_ID_NOTFOUND(115), NOCATEGORIES_FOUND(
			116), NOSUBCATEGORIES_FOUND(117), NOACC_FOUND(118), NOVENDOR_FOUND(
			119), NOACCSUBCATDATA_FOUND(120), NOCATACCDATA_FOUND(121), NOARTICLE_FOUND(
			122), NOSTONECATDATA_FOUND(123), NOSTONESUBCATDATA_FOUND(124), VALUATIONSLIPDETAILS_NOTFOUND(
			125), ORDERITEM_NOT_FOUND(126), INVALID_INPUTDATA(127), VALUATION_VALUATE(
			128), VALUATION_MATERIALIZATION(129), UNABLE_TO_FETCH_ORDER(130), TV_NOT_CREATED(
			131), ORDER_CREDIT_NOT_CREATED(132), ATTACHED_VALUATION_SLIP(133), ACKNOWLEDGED_TV(
			134), ALREADY_CONFIRMED_ORDER(135), UNELIGIBLE_CASHIER_CONFIRMATION_ORDER(
			136), UNELIGIBLE_STOREHEAD_CONFIRMATION_ORDER(137), SE_DESIGN_UPDATE_FAILED(
			138), PURITY_BETWEEN_RANGE(139), CUSTOMER_APPROVAL_DONE(140), SE_APPROVAL_DONE(
			141), ORDER_CP_SP_FAILURE(142), CASHIER_MA_FAILURE(143), CASHIER_RECONCILIATION_FAILURE(
			144), CASHIER_TO_CASHIER_TRANSFER_FAILURE(145), CASHIER_TO_CASHIER_CANCEL_FAILURE(
			146), TRANSIT_NOT_CREATED(147), TRANSIT_MA_FAILURE(148), NO_VALID_TRANSIT_ORDERITEMS(
			149), ST_INSERT_FAILURE(150), MIV_MA_FAILURE(151), TV_MA_FAILURE(
			152), MRV_MA_FAILURE(153), PB_MA_FAILURE(154), GV_CREATION_FAILURE(
			155), GV_AGREEMENT_SAVE_FAILURE(156), GV_AGREEMENT_UPDATION_FAILURE(
			157), GV_AGREEMENT_ID_NOTFOUND(158), GV_ISSUED_FOR_AGREEMENT(159), GV_AGREEMENT_PERIOD_INVALID(
			160), INVALID_PREPAID_GV_NUM(161), SCHEME_NAME_NOT_AVAILABLE(162), SAVINGSPLAN_CREATION_FAILURE(
			163), SAVINGS_PLAN_NO_NOTFOUND(164), PDC_CREATION_FAILURE(165), PDC_UPDATION_FAILURE(
			166), MRV_SA_FAILURE(167), IS_PDC_EXIST(168), SMALL_ORDER_CREATION_FAILURE(
			169), SMALL_ORDER_UPDATE_FAILURE(170), SMALL_ORDER_GR_CREATE_SUCCESS(
			171), SMALL_ORDER_GR_CREATE_FAILURE(172), CREDIT_TO_ACC_FOR_EXISTING_ORD_FAIL(
			173), ORDER_NOT_UPDATED(174), ORDER_LINE_ITEM_NOT_UPDATED(175), SOP_ALREADY_BILLED(
			176), SB_FAILURE(177), CANNOT_SETTLE_BILL(178), BILLED_ORDER(179), INVALID_SB(180), NO_DISCOUNT(181), NO_STATES_FOUND(182), NO_CITIES_FOUND(183), NOT_ABLE_TO_MATERIALIZE(184),
	        UNABLE_TO_SAVE_METAL_RETURN(185),UNABLE_TO_DELETE_METAL_RETURN(186),INSUFFICIENT_BALANCE(187),UNABLE_TO_CONFIRM_METAL_RETURN(188),CANNOT_CREATE_DUPLICATE(189),
	        PAN_NUMBER(190),APP_BILL_FAILURE(200), SESSION_EXPIRED(201),NO_VALID_TRANSIT_STOCKITEMS(202), NO_VALID_TRANSIT_CREDIT_ACCOUNT_ITEMS(203),TAX_STRUCTURE_NOT_FOUND(204),
            ISSUE_LOYALTY_CARD_FAILURE(205), NOT_ASSIGN_CUSTOMER_LOYALTY_FAILURE(206), LOYALTY_IN_ACTIVE(207),INVALID_LOYALTY_CARD_NO(208),
            SETTLEMENT_OF_ORDER(209),SB_SUPERVISOR_FAILURE(210);

	private final int number;

	private SalesCode(int number) {
		this.number = number;
	}

	@Override
	public int getNumber() {
		return number;
	}

}
